### ISSUE TITLE
Compile failure on Windows7 vs 2010

### ISSUE THREAD

**Issue by pauldorn** [mscdex/cap#18]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  binding.cc
..\src\binding.cc(249): warning C4267: '=' : conversion from 'size_t' to 'unsig
ned int', possible loss of data [c:\Users\Paul Dorn\Workspace\cap\build\cap.vcx
proj]
..\src\binding.cc(336): warning C4353: nonstandard extension used: constant 0 a
s function expression.  Use '__noop' function intrinsic instead [c:\Users\Paul
Dorn\Workspace\cap\build\cap.vcxproj]
..\src\binding.cc(387): warning C4344: behavior change: use of explicit templat
e arguments results in call to 'v8::Local<T> NanNew<v8::String,char*>(A0)' [c:\
Users\Paul Dorn\Workspace\cap\build\cap.vcxproj]
          with
          [
              T=v8::String,
              A0=char *
          ]
          but the regular function 'v8::Local<T> NanNew(const char *)' is a bet
  ter match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *)' to be called then y
  ou need to make it an explicit specialization
          with
          [
              T=v8::String
          ]
..\src\binding.cc(393): error C2664: 'uv_async_init' : cannot convert parameter
 3 from 'void (__cdecl *)(uv_async_t *,int)' to 'uv_async_cb' [c:\Users\Paul Do
rn\Workspace\cap\build\cap.vcxproj]
          None of the functions with this name in scope match the target type
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Users\Paul Dorn\AppData\Roaming\np
m\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Paul Dorn\\Ap
pData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Paul Dorn\Workspace\cap
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok

I'm looking at what might have caused this but it will take some time since I need to wrap my head around NAN.

**Comment by pauldorn** [comment]
Package version of NAN is 1.5.3, also tried 1.6.2

**Comment by pauldorn** [comment]
NodeJS 0.12.0

**Comment by pauldorn** [comment]
Adding an explicit cast gets past the error on build.  It will be a while before I can test if it actually runs this way.
#ifdef _WIN32
      r = uv_async_init(uv_default_loop(), &obj->async, (uv_async_cb)cb_packets);

**Comment by mscdex** [comment]
Verified with io.js 1.1.0 too, typecast added in 960d4d0b348 and v0.0.12. Thanks for the report.
