### ISSUE TITLE
Decoding Long TCP Packets

### ISSUE THREAD

**Issue by karldd** [mscdex/cap#24]
Firstly thanks for the great library, very helpful!

I'm feeding in data captured from Wireshark, and I've found that large packets (in this case over 60,000 bytes) aren't being decoded correctly. Small packets work as expected.

In the example below, the return value from `decoders.IPV4()` gives `info.totallen` as zero:
https://gist.github.com/karldd/7892a8dd08543e99e954

Ideally all TCP packets are below 1500 bytes, but apparently some configurations go well over this.

**Comment by mscdex** [comment]
Is `packet` in that gist the result of `buffer.slice(0, nbytes)` as indicated in the example in the readme?

**Comment by mscdex** [comment]
Also, what platform are you using to test this?

**Comment by karldd** [comment]
@mscdex Thanks for the prompt reply. `packet` is exported from WireShark directly for the purpose of making a self-contained example. I am using your library to listen to live packets, but for testing purposes I record live data with WireShark, then play it back using [pcap-parser](https://github.com/kunklejr/node-pcap-parser). Your `decoder` works really well for 'regular' sized packets.

I'm using Windows.

**Comment by mscdex** [comment]
Do you have the original pcap that you can share?

It would also be helpful to get the value of `buffer.slice(0, nbytes)` with `cap` in addition to wireshark, just to verify that the two agree with each other and that wireshark isn't doing any kind of packet munging.

**Comment by karldd** [comment]
The original pcap is quite big, so I created a subset with 10 packets. 3 of the packets are large (over 1500? bytes) and cause the test case (GIST link below) to fail.

[LongTCP.pcap](https://drive.google.com/file/d/0B2n71sIMvg7lbkpVUW9kTlFHeWs/view)
[GIST Test case](https://gist.github.com/karldd/5980f84567537781809e)

**Comment by mscdex** [comment]
As Wireshark suggests, it does seem that this may be due to [TSO](http://en.wikipedia.org/wiki/Large_segment_offload). I've added a simple workaround in 68151d74b1 for this when this happens.

However the "expected" TCP packet with length 64782 must be wrong as not even Wireshark shows that number anywhere in the pcap file. Everything else seems to match though after that commit.

**Comment by karldd** [comment]
Great! That works like a charm. The expected 64782 turns out to be a mistake on my part, I misread a field in Wireshark.

Thanks again!
