### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by sandeepbs39** [mscdex/cap#26]
when i try to run the program system gets crack giving ASSERTION FAILED
![capture](https://cloud.githubusercontent.com/assets/12541872/7795180/f777867c-02ef-11e5-8d97-45561b858838.PNG)

**Comment by aritzsanc** [comment]
I have the same problem.
Even when running the example code to "Capture and decode all outgoing TCP data packets destined for port 80 on the interface for 192.168.0.10"
Same error, same file, same line.

**Comment by sandeepbs39** [comment]
Remove tht line and rebuild its work for me
