### ISSUE TITLE
Feature request: ARP decoder

### ISSUE THREAD

**Issue by TravelingTechGuy** [mscdex/cap#31]
Any chance you can add an ARP decoder (or sample code on how to decode an ARP packet?)
Thanks!

**Comment by mwittig** [comment]
See https://github.com/mscdex/cap/issues/39#issuecomment-250986604

**Comment by mscdex** [comment]
The decoders included with this module are not meant to be a complete set as there are many network protocols out there, however an ARP decoder was added as previously pointed out.
