### ISSUE TITLE
question: example for sending packet with right addresses

### ISSUE THREAD

**Issue by zh99998** [mscdex/cap#32]
i want to send a udp packet in windows. the source port i needed is using by another program so i can't use normal dgram.

i'm using raw-socket (https://www.npmjs.com/package/raw-socket) to do it now, it works well but will trigger UAC each time. and i find wireshark can run as normal user after install winpcap as service. then i'm trying to use cap to send this packet.

the "Send an arbitrary packet" example writes MAC address and source IP address directly in program, which can't work in real world. and i can't find how it can be automatically detected.

could you add a example for sending a udp packet with detected addresses that will works in real-world?

**Comment by mscdex** [comment]
Well if you don't have the MAC address from captured traffic, then you could first look up the IP address in the OS's existing ARP cache (e.g. call out to and parse `arp` as a child process). There are modules on npm that can do this parsing for you (even cross-platform). If the host is found in the cache you've got the MAC address and you're all set. If it isn't found, then you could either perform some sort of network request for that IP address (e.g. `ping`) to implicitly cache the MAC address (assuming the host could be found) *or* craft and parse your own [ARP packets](https://en.wikipedia.org/wiki/Address_Resolution_Protocol) using `cap.send()`.

**Comment by zh99998** [comment]
firstly, how to get outgoing device, source ip address and gateway address.

in linux, we have ip route get x.x.x.x but i can't find something similar under windows....

**Comment by mscdex** [comment]
@zh99998 Sorry, I'm not sure. You may look into using something like PowerShell in a child process to gather the necessary routing info (sorted by metric) and then iterate over the routes, applying the mask to x.x.x.x to determine if the route matches with first route match wins. It's definitely more tedious, but I'm not really a Windows/PowerShell expert, so there could be an easier way....
