### ISSUE TITLE
Question: use bufSize or setMinBytes ?

### ISSUE THREAD

**Issue by alexandrubau** [mscdex/cap#35]
I don't quite understand the difference between the two. Isn't it the same if I set **bufSize** to 0 and no longer use **setMinBytes** ?

From the readme:

**bufSize** is the size of the internal buffer that libpcap uses to temporarily store packets until they are emitted

**setMinBytes**(< integer >nBytes) - (void) - (Windows ONLY) This sets the minimum number of packet bytes that must be captured before the full packet data is made available. If this value is set too high, you may not receive any packets until WinPCap's internal buffer fills up.

Can you explain a little bit better what they do ?

Thanks for your help

**Comment by mscdex** [comment]
`setMinBytes()` maps to [`pcap_setmintocopy()`](https://www.winpcap.org/docs/docs_412/html/group__wpcapfunc.html#gab14ceacbf1c2f63026416dd73f80dc0d) which says:

<blockquote>
Set the minumum amount of data received by the kernel in a single call.

pcap_setmintocopy() changes the minimum amount of data in the kernel buffer that causes a read from the application to return (unless the timeout expires). If the value of size is large, the kernel is forced to wait the arrival of several packets before copying the data to the user. This guarantees a low number of system calls, i.e. low processor usage, and is a good setting for applications like packet-sniffers and protocol analyzers. Vice versa, in presence of a small value for this variable, the kernel will copy the packets as soon as the application is ready to receive them. This is useful for real time applications that need the best responsiveness from the kernel. pcap_open_live() sets a default mintocopy value of 16000 bytes.
</blockquote>

Where `setMinBytes()` controls a Windows kernel-level buffer, `bufSize` controls a userspace-level buffer for storing packets.

**Comment by alexandrubau** [comment]
Thank you very much @mscdex for your time. I really appreciate it.
