### ISSUE TITLE
I have try to install CAP but npm gave error saying " this is mostly problem with cap  package not with npm itself ".

### ISSUE THREAD

**Issue by dheerajreddy1** [mscdex/cap#38]
I am using node v4.2.4
                  npm  v2.14.12
                  WinPcap 4.1.3 
error is showing that in my system node-gyp rebuild has failed.

**Comment by mscdex** [comment]
Do you have an appropriate compiler environment installed?

To compile any node addon you will need to *either*:

1. Install just the [Visual C++ build tools package](http://go.microsoft.com/fwlink/?LinkId=691132). This is a technical preview, but supposedly it has been working for people (and it is a much smaller installation too). According to [this PR](https://github.com/nodejs/node-gyp/pull/867) you will need to select **Custom install** and select *both* Windows 8.1 and Windows 10 SDKs. Additionally, Windows Vista/7 users may need .NET framework 4.5.1.

2. Install Visual C++ Express (for Windows Desktop), preferably 2015.

**Comment by dheerajreddy1** [comment]
i have installed the softwares that u have mentioned above but i feel result is still unchanged. Below i am providing the error code just have glance over it .

C:\Users\SESA391442\PTI_0022_Automation_tool\LightWebApp\js\tests\express\node_m
odules>npm install cap
\
> cap@0.1.1 install C:\Users\SESA391442\PTI_0022_Automation_tool\LightWebApp\js\
tests\express\node_modules\cap
> node-gyp rebuild


C:\Users\SESA391442\PTI_0022_Automation_tool\LightWebApp\js\tests\express\node_m
odules\cap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\nod
e_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" reb
uild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366
,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
 TargetFrameworkVersion or PlatformToolset may be set to an invalid version num
ber. [C:\Users\SESA391442\PTI_0022_Automation_tool\LightWebApp\js\tests\express
\node_modules\cap\build\cap.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\SESA391442\PTI_0022_Automation_tool\LightWebApp\js\t
ests\express\node_modules\cap\build\cap.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\SESA391442\PTI_0022_Automation_tool\LightWebApp\js\tests\e
xpress\node_modules\cap
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "cap"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! cap@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SESA391442\PTI_0022_Automation_tool\LightWebApp\js\tests\e
xpress\node_modules\npm-debug.log

**Comment by mscdex** [comment]
Try executing `npm config set msvs_version 2015` once and then try to reinstall `cap`.
