### ISSUE TITLE
Trying to sniff ARP packets using cap

### ISSUE THREAD

**Issue by dheerajreddy1** [mscdex/cap#39]
Its not an issue . I know u didnt made a code to sniff ARP packets. But actually looking at your decoder file I just made some piece of code to sniff ARP packets  but i didn't got output . I will attach code below. please help me if you found any errors.

``` javascript
// Internet Layer Protocols ====================================================
exports.ARP = function(b, offset) {
  offset || (offset = 0);   
  var origoffset = offset, i;
  var ret = {
    info: {
      hardwareAddr: undefined,
      protocol: undefined,
      hdrlen: undefined,
      protlen: undefined,
      opcode: undefined,
      senderMac: undefined,
      senderIp: undefined,
      targetMac: undefined,
      targetIp: undefined,
    },
    hdrlen: undefined,
    offset: undefined
  };
  ret.info.hardwareAddr = b.readUInt16BE(offset, true);
  offset += 2;
  ret.info.protocol = b.readUInt16BE(offset, true);
  offset += 2;
  ret.info.hdrlen = b.readUInt16BE(offset, true);
  offset += 1;
  ret.info.protlen = b.readUInt16BE(offset, true);
  offset += 1;
  ret.info.opcode = b.readUInt16BE(offset, true);
  offset += 2;
  ret.info.senderMac = b.toString('hex', offset, offset + 6);
  offset += 6;
  ret.info.senderIp = b.toString('hex', offset, offset + 4);
  offset += 4;
  ret.info.targetMac = b.toString('hex', offset, offset + 6);
  offset += 6;
  ret.info.targetIp = b.toString('hex', offset, offset + 4);
  offset += 4;
  ret.offset = offset;
  return ret;
};  
```

**Comment by mscdex** [comment]
Can you also show the code you're using that uses this function?

**Comment by dheerajreddy1** [comment]
`var Cap = require('cap').Cap,
    decoders = require('cap').decoders,
    PROTOCOL = decoders.PROTOCOL;
    c = new Cap(),
    device = '\\Device\\NPF_{B72765C8-CD73-45E0-8723-BD121163DC18}',
    filter = '',
    bufSize = 10 * 1024 * 1024,
    buffer = new Buffer(65535);
	console.log("buffer");
	c.on('packet', function(nbytes, trunc) 
	{
		console.log('packet: length ' + nbytes + ' bytes, truncated? '
		+ (trunc ? 'yes\r\n' : 'no\r\n'));

		var linkType = c.open(device, filter, bufSize, buffer);
		if (linkType === 'ETHERNET') 
		console.log('Decoding ARP ...');	
		{
			var ret = decoders.Ethernet(buffer);

			if (ret.info.type === PROTOCOL.ETHERNET.ARP)
			{
				console.log('Decoding ARP ...');

				ret = decoders.ARP(buffer, ret.offset);
				console.log("sender mac address:", ret.info.hardwareAddr);
				console.log("sender Ip Address:", ret.info.senderIp);
				
			}
		}
	});
	
	
	
	`

**Comment by mscdex** [comment]
Your `c.open()` is in the wrong place. You won't get any `packet` events until you `c.open()` first, so place that outside of your `packet` event handler.

**Comment by dheerajreddy1** [comment]
actually i used same code which you are mentioned in website. I am sniffing UDP packets. if you dont mind can please edit my code and post it.
below code i used to sniff UDP packets.
`var Cap = require('cap').Cap,
    decoders = require('cap').decoders,
    PROTOCOL = decoders.PROTOCOL;
 
var c = new Cap(),
    device = '\\Device\\NPF_{B72765D8-CD73-45E0-8723-BD121163DC18}',
    filter = 'udp and src port 67 or src port 68 ',
    bufSize = 10 * 1024 * 1024,
    buffer = new Buffer(65535);
 
	var linkType = c.open(device, filter, bufSize, buffer);
	c.setMinBytes && c.setMinBytes(0);
	c.on('packet', function(nbytes, trunc) 
	{
		console.print('packet: length ' + nbytes + ' bytes, truncated? '
		+ (trunc ? 'yes\r\n' : 'no\r\n'));
		// raw packet data === buffer.slice(0, nbytes) 
		if (linkType === 'ETHERNET') 
		{
			var ret = decoders.Ethernet(buffer);
			if (ret.info.type === PROTOCOL.ETHERNET.IPV4) 
			{
				console.print('Decoding IPv4 ...\r\n');
				ret = decoders.IPV4(buffer, ret.offset); 
				console.print('from: ' + ret.info.srcaddr + ' to ' + ret.info.dstaddr );
				console.print('ETHERNET PACKAGE:');
				console.print(buffer);
				console.print('\n\n');
			//	console.print('retOffset:');
			//	console.print(ret.offset);
			//	console.print('\n\n');
				if (ret.info.protocol === PROTOCOL.IP.TCP) 
				{
					var datalen = ret.info.totallen - ret.hdrlen;
					console.print('Decoding TCP ...');
					ret = decoders.TCP(buffer, ret.offset);
					console.print(' from port: ' + ret.info.srcport + ' to port: ' + ret.info.dstport );
					console.print('TCP PACKAGE:');
					datalen -= ret.hdrlen;						// console.log(buffer.toString('binary', ret.offset, ret.offset + datalen));
			    } 
				else if (ret.info.protocol === PROTOCOL.IP.UDP) 
				{   
					console.print('Decoding UDP ...\r\n');
					ret = decoders.UDP(buffer, ret.offset);
					console.print(' from port: ' + ret.info.srcport + ' to port: ' + ret.info.dstport );
					console.print('\n\n');`

**Comment by dheerajreddy1** [comment]
yeah... i got it  thank. Is there any filter in cap module  to filter certain "mac address" . can you  add my code to your source code soc that  it will be helpful to everyone . directly they will get ARP packets instead of going for some other  modules.

**Comment by mscdex** [comment]
As far as the filter syntax goes, it's the same syntax that tcpdump uses. So to look for a particular mac address you should be able to use something like `'ether host aa:bb:cc:dd:ee:ff'`.

**Comment by dheerajreddy1** [comment]
actually now able to see ARP packets and  it consists of both ethernet-2 and 802.3 packets i saw in wireshark. But using cap module i am sniffing only ethernet-2 packets.

**Comment by mscdex** [comment]
You'd have to write a separate decoder. 802.3 is fairly similar to ethernet-2 though, so you could re-use some code. See [this SO answer](http://networkengineering.stackexchange.com/a/5302) for details.

**Comment by dheerajreddy1** [comment]
Sorry i didn’t understand your message clearly, my query is …. Is  CAP module can  sniff 802.3 packets ? 
If it doesn’t where  should i develop code . can you help me with that. Right now  i am able to sniff only ethernet-2 packets.I have just used “arp” as filter in function code.

**Comment by dheerajreddy1** [comment]
The only difference i found between ethernet 2 and 802.3 is SNAP.
SNAP is present in 802.3 frame packet and it won’t be ethernet-2 frame.

**Comment by mscdex** [comment]
Are you seeing `packet` events for the 802.3-encapsulated packets? As far as I know the `'arp'` filter should emit packets for both types, with the difference being in the decoding of the packets as I previously noted (e.g. if the type/len field is >= 1536, it's Ethernet II). The current ethernet decoder only performs simple type/length field checking and does not handle SNAP or other fields for non-Ethernet II encapsulation.

**Comment by dheerajreddy1** [comment]
NO ..i am not getting 802.3 packets in any format.

**Comment by dheerajreddy1** [comment]
so now what shall I add to typelen in ethernet code to decode the packets...???

**Comment by dheerajreddy1** [comment]
what "linkType" does in function code. actually i have removed ethernet part in decoders and i have added IEEE8023 . but when i try to print linkType it still printing as ETHERNET. So  I am not understanding where i have to change ETHERNET TO IEEE8023.

**Comment by mscdex** [comment]
Do you have a reliable way of duplicating these packets that I can use?

**Comment by dheerajreddy1** [comment]
since I am generating packets with local board so i can't share the packets. If you want we can make webex meeting

**Comment by dheerajreddy1** [comment]
Hello...mscdex I have one doubt regarding filters , before i faced a issue regarding filtering of 802.3 ARP packets. your module is able to  get all ethernet 2 packets but its not filtering 802.3 packets. so I have used one more filter consists of mac address and '0806' ARP protocol number after closing first filter  'c.close(device, filter1, bufSize, buffer);'  . BUt the issue right now i am facing when i gave second filter the DHCP OFFER and DHCP ACK are not filtering i.e (packets which are coming from another mac address guy). IF you have any idea on it please give me some hint...

**Comment by mwittig** [comment]
@mscdex I am wondering whether or not you progressed on this one. As I need an ARP encode for my project I have roled my own encoding function based on on the snippet @dheerajreddy1 posted. My implementation is not perfect as it might not cover all cases, but it is comparable to what [node-pcap](https://github.com/mranney/node_pcap/blob/master/decode/arp.js#L17-L34) has. If you like my proposal I am happy to create a pull request.

```
exports.ARP = function(b, offset) {
  offset || (offset = 0);
  var ret = {
    info: {
      hardwareaddr: undefined,
      protocol: undefined,
      hdrlen: undefined,
      protlen: undefined,
      opcode: undefined,
      sendermac: '',
      senderip: '',
      targetmac: '',
      targetip: ''
    },
    offset: undefined
  };
  ret.info.hardwareaddr = b.readUInt16BE(offset, true);
  offset += 2;
  ret.info.protocol = b.readUInt16BE(offset, true);
  offset += 2;
  ret.info.hdrlen = b.readInt8(offset, true);
  offset += 1;
  ret.info.protlen = b.readInt8(offset, true);
  offset += 1;
  ret.info.opcode = b.readUInt16BE(offset, true);
  offset += 2;
  if (ret.info.hdrlen == 6 && ret.info.protlen == 4) {
    for (i = 0; i < 6; ++i) {
      ret.info.sendermac += ('00' + b[offset++].toString(16)).substr(-2);
      if (i < 5)
        ret.info.sendermac += ':';
    }

    for (i = 0; i < 4; ++i) {
      ret.info.senderip += b[offset++].toString(10);
      if (i < 3)
        ret.info.senderip += '.';
    }

    for (i = 0; i < 6; ++i) {
      ret.info.targetmac += ('00' + b[offset++].toString(16)).substr(-2);
      if (i < 5)
        ret.info.targetmac += ':';
    }

    for (i = 0; i < 4; ++i) {
      ret.info.targetip += b[offset++].toString(10);
      if (i < 3)
        ret.info.targetip += '.';
    }
  }
  ret.offset = offset;
  return ret;
};
```

**Comment by mscdex** [comment]
@mwittig If you have a working decoder, feel free to open a PR.
