### ISSUE TITLE
How hard is it to implement IPv6?

### ISSUE THREAD

**Issue by sascha1337** [mscdex/cap#44]

**Comment by mscdex** [comment]
What do you mean? An IPv6 decoder or? There should be an IPv6 decoder already.

**Comment by sascha1337** [comment]
```
Unsupported Ethertype: IPV6
packet: length 100 bytes, truncated? no
Unsupported Ethertype: IPV6
packet: length 1412 bytes, truncated? no
Unsupported Ethertype: IPV6
packet: length 1412 bytes, truncated? no
```

Thats what i'm talking about

**Comment by mscdex** [comment]
Yes, so just add another conditional that checks `ret.info.type === PROTOCOL.ETHERNET.IPV6` and decodes using the IPv6 decoder instead in that case.
