### ISSUE TITLE
Is there a way to get the amount of traffic during the last/next second?

### ISSUE THREAD

**Issue by SlickNutter** [mscdex/cap#50]
I'm writing a little bit of code to monitor the amount of traffic going in/out of a computer.

**Comment by mscdex** [comment]
If you're talking about *all* network traffic, no. For that you'd be better off using some other mechanism (possibly something provided by the OS).

If you're talking about for a specific capture filter, you'd have to calculate that yourself as data comes in.

**Comment by SlickNutter** [comment]
Thank you for the quick response!
Do you know of any possibility that Windows offers for this?

**Comment by mscdex** [comment]
I'm not a Windows person, but a quick google search shows querying [Win32_PerfRawData_Tcpip_NetworkInterface](https://technet.microsoft.com/en-us/security/aa394340(v=vs.80)) in WMI might get you what you want. If not, there might be some other things you can query in WMI to get the info you're looking for.
