### ISSUE TITLE
Packets through port 443

### ISSUE THREAD

**Issue by theunreal** [mscdex/cap#55]
Hi,
I'm trying to view packets through port 443 using the following filter:

filter = 'tcp and dst port 443',

I'm using the same code as in the example:

```
c.on('packet', function (nbytes, trunc) {
    if (linkType === 'ETHERNET') {
      var ret = decoders.Ethernet(buffer);
      if (ret.info.type === PROTOCOL.ETHERNET.IPV4) {
        ret = decoders.IPV4(buffer, ret.offset);
        if (ret.info.protocol === PROTOCOL.IP.TCP) {
          var datalen = ret.info.totallen - ret.hdrlen;
          ret = decoders.TCP(buffer, ret.offset);
          datalen -= ret.hdrlen;
          const offset = buffer.toString('binary', ret.offset, ret.offset + datalen);
```

the problem is that `offset ` echos very strange output, see this:

![image](https://user-images.githubusercontent.com/6171883/35183041-30fea326-fde8-11e7-87ca-e473eb74587e.png)

Is there something I'm missing with the decoder?

Thanks

**Comment by mscdex** [comment]
HTTPS traffic is encrypted. What else would you expect to see?

**Comment by theunreal** [comment]
@mscdex I expect to have a method to decrypt such traffic,
I tried to put the packet raw data in a packet decode service like https://www.gasmi.net/hpd/ and it decrypted the packet. I'm not sure how to decrypt such packet and what the website above does behind the scenes.

**Comment by mscdex** [comment]
You're asking how to MITM connections then, which is outside the scope of this module.

**Comment by theunreal** [comment]
I didn't mean to MITM, the hostname in the handshake of the encrypted traffic is not encrypted.
I just found out that it's visible using the library - I'm closing this issue

**Comment by mscdex** [comment]
For that you'd need to write a TLS protocol decoder. The decoders provided by this module exist to get you to the application layer. Anything at the application layer is up to the users of this module because there are so many protocols at that layer and I do not want to maintain such decoders.
