### ISSUE TITLE
failing at building on windows

### ISSUE THREAD

**Issue by fakirpic** [mscdex/cap#59]
PS C:\xampp\htdocs\npcap> npm install cap

> cap@0.2.0 install C:\xampp\htdocs\node_modules\cap
> node-gyp rebuild

C:\xampp\htdocs\node_modules\cap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(2455): error C2144: syntax error : 'int' should be preceded by ';' (..\
src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(2455): error C4430: missing type specifier - int assumed. Note: C++ doe
s not support default-int (..\src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4122): error C2610: 'v8::WasmCompiledModule::TransferrableModule::Trans
ferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be default
ed (..\src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4125): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::W
asmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special
member function which can be defaulted (..\src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4200): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleOb
jectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulte
d (..\src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4205): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModu
leObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which
 can be defaulted (..\src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4238): error C2610: 'v8::WasmModuleObjectBuilder::WasmModuleObjectBuild
er(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\binding.cc) [C:\x
ampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4240): error C2610: 'v8::WasmModuleObjectBuilder &v8::WasmModuleObjectB
uilder::operator =(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\b
inding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4516): error C2146: syntax error : missing ';' before identifier 'size_
t' (..\src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
c:\users\asus\.node-gyp\9.2.0\include\node\v8.h(4516): error C4430: missing type specifier - int assumed. Note: C++ doe
s not support default-int (..\src\binding.cc) [C:\xampp\htdocs\node_modules\cap\build\cap.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
58:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\node_modules\cap
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\package.json'
npm WARN htdocs No description
npm WARN htdocs No repository field.
npm WARN htdocs No README data
npm WARN htdocs No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2018-02-26T07_12_01_572Z-debug.log
PS C:\xampp\htdocs\npcap>

**Comment by mscdex** [comment]
You need to use [VS2015 or newer for building addons with node v9.0.0+](https://github.com/nodejs/node/commit/2062a69879).
