### ISSUE TITLE
CAP Module throwing return process.dlopen(module,path(filename)

### ISSUE THREAD

**Issue by RoshDevi** [mscdex/cap#60]
Hi,

Node -version : 9.6.1
npm -version : 5.6.0

I have first installed Visual studio 2015 using "npm install --global --production windows-build-tools".
And I have installed cap module using "npm install cap". The cap module got installed in the node_modules folder I have. 

Later, I tried to run the example you have provided. It is throwing the error as seen in screensho
![issue](https://user-images.githubusercontent.com/36291405/36723531-878cb2d0-1bd6-11e8-90ba-b762be4cd624.PNG)
t

**Comment by mscdex** [comment]
Can you show the text displayed during `npm install cap` ?

**Comment by RoshDevi** [comment]
![issue1](https://user-images.githubusercontent.com/36291405/36728745-e19f2f94-1be7-11e8-844c-cfe9e798f6ca.png)
 
This is what is getting displayed while installing

**Comment by mscdex** [comment]
If you change to the 'cap' directory and run `npm test`, does that work?

**Comment by MadScripter** [comment]
As stated in the requirements, you need to install [Npcap with WinPcap compatibility](https://nmap.org/npcap/)

**Comment by mscdex** [comment]
Ah yes, that could cause it as well. Thank you for the suggestion.

**Comment by RoshDevi** [comment]
Yes, The issue is resolved with the installation of WinPcap. Thank you @MadScripter , @mscdex

**Comment by woxman** [comment]
> WinPcap

how??

please help me this problem
