### ISSUE TITLE
Installing cap module

### ISSUE THREAD

**Issue by ohmtrivedi** [mscdex/cap#64]
Hi,
I am facing issue with installing cap via npm.
`C:\Users\Ohm\Desktop\My Stuff\FAU Stuff\MS Thesis\Programming\node_modules\cap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Ohm\Anaconda3\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ohm\Desktop\My Stuff\FAU Stuff\MS Thesis\Programming\node_modules\cap
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Ohm\Desktop\My Stuff\FAU Stuff\MS Thesis\Programming\package.json'
npm WARN Programming No description
npm WARN Programming No repository field.
npm WARN Programming No README data
npm WARN Programming No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ohm\AppData\Roaming\npm-cache\_logs\2018-04-10T06_35_11_811Z-debug.log`

npm version: 5.3.0
Windows 10 OS

I did set up the PYTHON environment variable separately and as part of PATH variable as well.

**Comment by mscdex** [comment]
This would be better posted to the [nodejs/node-gyp issue tracker](https://github.com/nodejs/node-gyp/issues) as this is not specific to this addon. However, as the error states, it didn't find the python executable at the specified path. Typically you do not need to set environment variables and such on Windows, just install Python 2.x normally and re-open any command prompt windows you had open.
