### ISSUE TITLE
Event for 'full packets'

### ISSUE THREAD

**Issue by Apuru** [mscdex/cap#67]
Hello, I'm new to using this. 

Is it there or is it possible to add an event for when a full packet is reassembled?

For example: The current event 'packet' activates when a packet is received. Large packets, such as ones compressed, may be sent in parts. One big part and one small part for example which would emit 2 events. It must be reassembled and then decompressed. Is it possible to add this as an event?

**Comment by mscdex** [comment]
All packets are passed directly from the packet capturing library, so no (TCP) reassembly is done. The end user will need to perform that if they need it.

**Comment by StephenGrider** [comment]
@mscdex Are there any examples of packet reassembly published in the repo?

**Comment by mscdex** [comment]
No
