### ISSUE TITLE
ERROE %1 Not windows 32 applications

### ISSUE THREAD

**Issue by halilarici** [mscdex/cap#71]
![ekran resmi 2018-07-29 17 31 57](https://user-images.githubusercontent.com/26468596/43367981-4a8651e8-935e-11e8-88df-a3d672315bbb.png)

**Comment by mscdex** [comment]
Two possibilities:

* A precompiled version of the addon is being used on the wrong platform
* Npcap is not installed

**Comment by halilarici** [comment]
I can install Npcap. But I was not solved :/ Please help me. I was trying maybe 48 hours.

**Comment by mscdex** [comment]
How did you install `cap`? If you simply copied an existing node_modules directory to another system, that may cause this error. Additionally, if you did actually execute 'npm install cap' on this particular system, can you post the actual console output?

**Comment by halilarici** [comment]
My mac : 
![screenshot mac 2018-07-30 00 16 56](https://user-images.githubusercontent.com/26468596/43370783-f6c194ac-938d-11e8-922b-2acc04e5816c.png)

Try windows pc : 
![screenshot windows 2018-07-30 00 18 03](https://user-images.githubusercontent.com/26468596/43370788-12c56520-938e-11e8-9845-606f3acad66d.png)

I use electronjs.

**Comment by halilarici** [comment]
Yeah solved win32 problem but this new problem :
![image](https://user-images.githubusercontent.com/26468596/43386567-b3dfdc2a-93ec-11e8-9295-907c1ea353c9.png)
