### ISSUE TITLE
deviceList() returning an empty array

### ISSUE THREAD

**Issue by NotDaymon** [mscdex/cap#74]
I just got everything installed, no issues at all, and started playing around with the example codes. Although, when running 

> var Cap = require('cap').Cap;
> 
> console.dir(Cap.deviceList());

deviceList() returns an empty array. Am I missing something here?

**Comment by mscdex** [comment]
Have you tried running with elevated privileges?

**Comment by NotDaymon** [comment]
> Have you tried running with elevated privileges?
Yeah, same result.

**Comment by NotDaymon** [comment]
> Which platform?
> 
> Also, does `os.networkInterfaces()` return information?

Windows 7 x64

`os.networkInterfaces()` does return my local connections.

**Comment by mscdex** [comment]
Did you install WinPcap or npcap?

**Comment by NotDaymon** [comment]
> Did you install WinPcap or npcap?

Yes, I have the latest release of WinPcap

**Comment by NotDaymon** [comment]
UPDATE: Reinstalling the latest release on WinPcap seemed to solve the issue. Something may have gone wrong during the installation. For future reference, I used WinPcap 4.1.3
