### ISSUE TITLE
How to get data of a TCP packet?

### ISSUE THREAD

**Issue by AlllenShen** [mscdex/cap#81]
I use example code in my project, but the data is all 0.
```
var datalen = ret.info.totallen - ret.hdrlen;
datalen -= ret.hdrlen;
console.log(buffer.toString('binary', ret.offset, ret.offset + datalen));
```
I don't know why datalen should minus hdrlen again.

And I can't understand what `ret.offset` actually means?Is that the start position of TCP/IP packet header?  cause i logged the raw buffer, find it starts with nonzero.

**Comment by mscdex** [comment]
`ret` is an object containing information as a result of parsing the data starting at the given starting offset. In this object, the offset in which the parser ended on is returned as `ret.offset`.

**Comment by mscdex** [comment]
If you're not seeing expected data, then perhaps the filter needs to be tweaked/corrected or you have the wrong network device opened.

**Comment by AlllenShen** [comment]
It means data behind `ret.offset` is the TCP/IP packet data. So `ret.offset` to `ret.offset + ret.hdrlen` is the headers of a TCP packet. Is that right?

**Comment by mscdex** [comment]
`ret.offset` points to where the TCP data *starts*. Each protocol parser only parses what's necessary for that protocol. So in the case of TCP it just parses the header. `ret.hdrlen` is the length of the TCP header.

All of these questions can be answered by reading [lib/Decoders.js](https://github.com/mscdex/cap/blob/2bb50be2dd6535ca03e915bff55a04c7c546dd65/lib/Decoders.js#L610-L674). The code in there is pretty straightforward.

**Comment by AlllenShen** [comment]
Thank you so much. This is my first time to try node, so do not konw where to find the actually implementing code. I've read `binding.cc` but found decoder is not implemented here.
