### ISSUE TITLE
It's possible to get packets from loopback interface on windows?

### ISSUE THREAD

**Issue by Giuan0** [mscdex/cap#87]

**Comment by mscdex** [comment]
If you install npcap with the loopback support option during its installation, you might be able to select the loopback interface that is created. `cap.deviceList()` should show it if it exists.

**Comment by Giuan0** [comment]
The loopback interface has a link of type of NULL instead of 'ETHERNET' on windows, wich had 4 bytes, since I'll only be getting IPV4 protocols for my usecase, jumping the first four bytes will be ok.

Thanks!
